# Generated by Django 2.2 on 2020-10-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.IntegerField(blank=True, default=None, max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Аватарка'),
        ),
    ]
