# Generated by Django 2.2 on 2020-10-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20201026_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
    ]
