# Generated by Django 2.2 on 2020-11-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20201026_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.FileField(blank=True, default=None, upload_to='users_avatars', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='person',
            name='relationship',
            field=models.CharField(choices=[('NO', 'Не определенно'), ('SNG', 'Холост'), ('REL', 'В отношениях'), ('ENG', 'Помолвлен(а)'), ('MRD', 'Женат/Замужем'), ('ILV', 'Влюблен(а)'), ('CMP', 'Все сложно')], default='NO', max_length=3, verbose_name='Статус отношений'),
        ),
    ]
