# Generated by Django 2.2 on 2020-11-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20201101_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='relationship',
            field=models.IntegerField(choices=[('NO', 'Не определенно'), ('SNG', 'Холост'), ('REL', 'В отношениях'), ('ENG', 'Помолвлен(а)'), ('MRD', 'Женат/Замужем'), ('ILV', 'Влюблен(а)'), ('CMP', 'Все сложно')], default=0, verbose_name='Статус отношений'),
        ),
    ]
