# Generated by Django 2.2 on 2020-11-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20201107_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='relationship',
            field=models.IntegerField(choices=[(0, 'Не определенно'), (1, 'Холост'), (2, 'В отношениях'), (3, 'Помолвлен(а)'), (4, 'Женат/Замужем'), (5, 'Влюблен(а)'), (6, 'Все сложно')], default=0, verbose_name='Статус отношений'),
        ),
    ]
