# Generated by Django 3.1.3 on 2020-11-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_auto_20201115_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
    ]
