# Generated by Django 3.1.3 on 2022-06-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_auto_20220608_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[['male', 'Мужской'], ['female', 'Женский']], default=None, max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
