# Generated by Django 2.2 on 2020-11-10 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Запрошено'), (1, 'Одобрено'), (2, 'Не друзья'), (3, 'Отменено')], default=0, verbose_name='Статус')),
                ('created_at', models.DateTimeField(verbose_name='Дата запроса')),
                ('confirmed_at', models.DateTimeField(verbose_name='Дата ответа')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_target', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Запрос в друзья',
                'verbose_name_plural': 'Запросы в друзья',
            },
        ),
    ]
