# Generated by Django 2.2 on 2020-11-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequests',
        ),
    ]
