# Generated by Django 3.1.3 on 2021-11-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_auto_20211128_2344'),
        ('communityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityNewsItem',
            fields=[
                ('newsitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newsapp.newsitem')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityapp.community', verbose_name='Сообщество')),
            ],
            options={
                'verbose_name': 'Новость сообщества',
                'verbose_name_plural': 'Новости сообщества',
                'ordering': ('-add_datetime',),
            },
            bases=('newsapp.newsitem',),
        ),
    ]
