# Generated by Django 3.1.3 on 2021-11-26 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityNewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='Текст Новости')),
                ('add_datetime', models.DateTimeField(auto_now=True, verbose_name='Дата Добавления')),
                ('image', models.FileField(blank=True, default=None, upload_to='news_images', verbose_name='Изображние')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityapp.community', verbose_name='Сообщество')),
            ],
            options={
                'verbose_name': 'Новость сообщества',
                'verbose_name_plural': 'Новости сообщества',
                'ordering': ('-add_datetime',),
            },
        ),
    ]
