# Generated by Django 3.1.3 on 2020-11-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messengerapp', '0003_chat_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чаты', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['pub_date'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
