# Generated by Django 3.1.3 on 2020-11-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messengerapp', '0005_chat_last_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-last_message',), 'verbose_name': 'Чаты', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('pub_date',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
