# Generated by Django 3.1.3 on 2022-05-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messengerapp', '0006_auto_20201118_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='chat_logos', verbose_name='Изображние'),
        ),
    ]
