# Generated by Django 3.1.3 on 2022-05-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messengerapp', '0007_chat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='messages', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='chat_logos', verbose_name='Изображение'),
        ),
    ]
