# Generated by Django 2.2 on 2020-11-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='text',
            field=models.TextField(max_length=1024, verbose_name='Текст Новости'),
        ),
    ]
