# Generated by Django 3.1.3 on 2020-11-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20201107_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ('-add_datetime',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
