# Generated by Django 2.2 on 2020-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20201118_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to='news_images', verbose_name='Изображние'),
        ),
    ]
