# Generated by Django 3.1.3 on 2020-12-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='news_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='newsapp.newsitem', verbose_name='Запись'),
        ),
    ]
