# Generated by Django 3.1.3 on 2020-12-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20201226_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='add_datetime',
            field=models.DateTimeField(verbose_name='Дата Добавления'),
        ),
    ]
