# Generated by Django 3.1.3 on 2021-11-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_auto_20201226_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Проверено модераторами'),
        ),
    ]
