# Generated by Django 3.1.3 on 2021-11-28 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0010_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='add_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата Добавления'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
