# Generated by Django 3.1.3 on 2022-05-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_auto_20211129_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='news_images', verbose_name='Изображение'),
        ),
    ]
